import type { NextPage } from "next";
import Layout from "../components/Layout";
import Head from "next/head";
import styles from "../styles/pages/Dashboard.module.scss";
import Timer from "../components/Timer";
import { useMoralis } from "react-moralis";
import { useEffect } from "react";

const Home: NextPage = () => {
  const time = new Date();
  time.setSeconds(time.getSeconds() + 1800); // In seconds (60 is one minute)
  const { enableWeb3, isWeb3Enabled, isWeb3EnableLoading } = useMoralis();

  useEffect(() => {
    if (!isWeb3Enabled && !isWeb3EnableLoading) {
      enableWeb3();
    }
  }, [isWeb3Enabled, isWeb3EnableLoading]);

  return (
    <>
      <Head>
        <title>Way Pay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.container}>
          <div className={styles.first__row}>
            <div>
              <div className={styles.header__container}>
                <span>Market Value of Treasury Asset</span>
                <p>$4,616,041</p>
              </div>
              <div
                style={{
                  width: "100%",
                }}
              >
                <div
                  className={styles.info__container}
                  style={{
                    marginBottom: "1.5rem",
                  }}
                >
                  <span>Total Supply</span>
                  <p>7,246,628.34</p>
                </div>
                <div className={styles.info__container}>
                  <span>Circulating Supply</span>
                  <p>5,621,301.17</p>
                </div>
              </div>
            </div>
            <div className={styles.timer__container}>
              <div>
                <span>WayPay Price</span>
                <p>$25.67</p>
              </div>
              <div>
                <Timer time={time} />
              </div>
              <span>Rebasing...</span>
            </div>
            <div>
              <div className={styles.header__container}>
                <span>WayPay Insurance Fund Value</span>
                <p>$1,132,274</p>
              </div>
              <div
                style={{
                  width: "100%",
                }}
              >
                <div
                  className={styles.info__container}
                  style={{
                    marginBottom: "1.5rem",
                  }}
                >
                  <span>MarketCap</span>
                  <p>$144,566,960</p>
                </div>
                <div className={styles.info__container}>
                  <span>Pool Value</span>
                  <p>$17,665,693</p>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.second__row}>
            <div className={styles.info__container}>
              <span># Value of Burn Pot</span>
              <p>1,631,019.3</p>
            </div>
            <div className={styles.info__container}>
              <span>$ Value of Burn Pot</span>
              <p>$41,810,431</p>
            </div>
            <div className={styles.info__container}>
              <span>% Burn Pot : Supply</span>
              <p>22.43%</p>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
